### DISCUSSION TITLE
Contamination Estimation Option for Samples with cross-contamination

### DISCUSSION THREAD

**Discussion by maotian06** [uclahs-cds/pipeline-call-sSNV#131] [Show and tell]
The current `Mutect2` pipeline can accept an extra option in the `input.yaml`, here is an example:
```
  tumor:
    - id: 'TWGSAMIN000001-T001-S01-F'
      BAM: path/to/bam
      contamination_table: path/to/calculatecontamination.table
```
This will filter some sSNV and potentially increase the accuracy of the Mutect2 caller when you have a sample with high cross-contamination. Here is the table shows the comparison result:
sample | contamination_level | filtered sSNV with `contamination-estimation-table` | Filtered Out Variant Counts
------- | ------- | ------- | ------- |
MTOSIMHO000033 | 0.13 | 28.8% | 177
MTOSIMHO000034 | 0.01 | 7.7% |  28
MTOSIMHO000035 |  0.58 | 9.1% |  842

@tyamaguchi-ucla  The reason why the proportion doesn't match the contamination level is that the total variants from different samples are different.
`MTOSIMHO000035` has much more variants than `MTOSIMHO000033` and `MTOSIMHO000034`.  I added the `Filtered Out Variant Counts` column here. I can look into the raw code to see how Mutect2 process the contamination level later.
