### ISSUE TITLE
standardize input structure

### ISSUE THREAD

**Issue by sorelfitzgibbon** [uclahs-cds/pipeline-call-sSNV#278]
standard structure, allowing BAM or VCF.  checking in methods that both are not provided

**Comment by sorelfitzgibbon** [comment]
vcf:
```
---
patient_id: 'TWGSAMIN000001'
dataset_id: 'TWGSAMIN'
input_tumor_id: 'S2_v1.1.5' # tumor ID in the VCF files must match this or 'TUMOR'
input_normal_id: 'HG002.N' # normal ID in the VCF files must match this or 'NORMAL'
input:
  VCF:
    muse: /hot/software/pipeline/pipeline-call-sSNV/Nextflow/development/test-input/MuSE-2.0.4_TWGSAMIN_S2-v1.1.5_SNV-pass.vcf.gz
    mutect2: /hot/software/pipeline/pipeline-call-sSNV/Nextflow/development/test-input/Mutect2-4.5.0.0_TWGSAMIN_S2-v1.1.5_all-pass.vcf.gz
    somaticsniper: /hot/software/pipeline/pipeline-call-sSNV/Nextflow/development/test-input/SomaticSniper-1.0.5.0_TWGSAMIN_S2-v1.1.5_hc.vcf.gz
    strelka2: /hot/software/pipeline/pipeline-call-sSNV/Nextflow/development/test-input/Strelka2-2.9.10_TWGSAMIN_S2-v1.1.5_SNV-pass.vcf.gz
```
bam:
```
---
patient_id: 'patient_id'
input:
  BAM:
    normal:
      - path: /path/to/normal.bam
    tumor:
      - path: /path/to/tumor.bam
        contamination_table: /path/to/contamination.table
```
